"""Add notification preferences to User model

Revision ID: 3b1ef74c2038
Revises: b5b01103b036
Create Date: 2024-12-17 07:59:43.366519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1ef74c2038'
down_revision = 'b5b01103b036'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('notification_time', sa.Integer(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE \"user\" SET notification_type = 'both', notification_time = 16")
    
    # Now make the columns non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
                            existing_type=sa.String(length=10),
                            nullable=False)
        batch_op.alter_column('notification_time',
                            existing_type=sa.Integer(),
                            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_time')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
