"""Add evening and morning notification preferences

Revision ID: 6e16eeb47967
Revises: 3b1ef74c2038
Create Date: 2025-01-09 09:47:43.934679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e16eeb47967'
down_revision = '3b1ef74c2038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add columns as nullable first
        batch_op.add_column(sa.Column('evening_notification', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('evening_notification_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evening_notification_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('morning_notification', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('morning_notification_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('morning_notification_type', sa.String(length=10), nullable=True))

    # Set default values for existing users
    op.execute("""
        UPDATE "user" SET 
        evening_notification = true,
        evening_notification_time = 18,
        evening_notification_type = 'both',
        morning_notification = true,
        morning_notification_time = 7,
        morning_notification_type = 'both'
    """)

    # Make columns non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('evening_notification',
                            existing_type=sa.Boolean(),
                            nullable=False)
        batch_op.alter_column('evening_notification_time',
                            existing_type=sa.Integer(),
                            nullable=False)
        batch_op.alter_column('evening_notification_type',
                            existing_type=sa.String(length=10),
                            nullable=False)
        batch_op.alter_column('morning_notification',
                            existing_type=sa.Boolean(),
                            nullable=False)
        batch_op.alter_column('morning_notification_time',
                            existing_type=sa.Integer(),
                            nullable=False)
        batch_op.alter_column('morning_notification_type',
                            existing_type=sa.String(length=10),
                            nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('morning_notification_type')
        batch_op.drop_column('morning_notification_time')
        batch_op.drop_column('morning_notification')
        batch_op.drop_column('evening_notification_type')
        batch_op.drop_column('evening_notification_time')
        batch_op.drop_column('evening_notification')

    # ### end Alembic commands ###